### ISSUE TITLE
Visualizing Alignment for Custom Dataset

### ISSUE THREAD

**Issue by helia2078** [justinkay/aldi#20]
Hello,

Thank you for your excellent work. In the "Additional Experiments" section, specifically subsection 1.2 "Visualizing Alignment," you provided a distribution of data in the feature space. I would like to know how I can generate a similar output for my own dataset to view the results at this level.

Could you please provide guidance on how to achieve this?

Thank you.

**Comment by justinkay** [comment]
Sure, we will add a script to reproduce those plots to the repo. Should be sometime in the next week or so. Will tag you when it's up.

**Comment by helia2078** [comment]
Thank you for your attention.

**Comment by helia2078** [comment]
Hello again, 
I use the code but I've got this error:
KeyError: "No object named 'ALDI' found in 'META_ARCH' registry!"

**Comment by justinkay** [comment]
Hi @helia2078, there may have been some changes in the code since you created your config files. We removed ALDI from the `META_ARCH_REGISTRY` in e977376 and instead you can just use whichever architecture the model is (by default, this is `GeneralizedRCNN`.

Check your config file for this line and remove it:
```META_ARCHITECTURE: "ALDI"```

**Comment by helia2078** [comment]
Thank you for your responding.
I also wandering that how can I fix this error too(when I use Visualizing sode):

[06/10 09:24:39 d2.checkpoint.detection_checkpoint]: [DetectionCheckpointer] Loading from /home/Codes/ALDI/output/aldi_best/model_final.pth ...
[06/10 09:24:39 fvcore.common.checkpoint]: [Checkpointer] Loading from /home/Codes/ALDI/output/aldi_best/model_final.pth ...
[06/10 09:24:40 fvcore.common.checkpoint]: Loading EMA weights as model starting point.
Traceback (most recent call last):
  File "/home/Codes/ALDI/tools/visualize_featurespace.py", line 124, in <module>
    launch(
  File "/home/Codes/ALDI/libs/detectron2/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "/home/Codes/ALDI/tools/visualize_featurespace.py", line 72, in main
    assert len(cfg.DATASET.TRAIN) == 1
  File "/home/miniconda3/envs/ALDI2/lib/python3.9/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: DATASET

**Comment by timmh** [comment]
@helia2078 thanks for letting us know. This was a typo which should be fixed by 8f14ba5.

**Comment by helia2078** [comment]
Thank you.
