### ISSUE TITLE
FloatingPointError: Predicted boxes or scores contain Inf/NaN. Training has diverged.

### ISSUE THREAD

**Issue by Autobot37** [justinkay/aldi#33]

**Comment by Autobot37** [comment]
# -*- coding: utf-8 -*-
"""sim10k-cityscapes_

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a9AcPNJTJzx_UwyIn_whqF3EgC2qNfO7
"""

!wget -O sim10k.tar.gz https://deepblue.lib.umich.edu/data/downloads/ks65hc58r

!wget --keep-session-cookies --save-cookies=cookies.txt --post-data 'username=shivasinghbagri37&password=ZPP?DEt4g!9@T!t&submit=Login' https://www.cityscapes-dataset.com/login/
!wget --load-cookies cookies.txt --content-disposition https://www.cityscapes-dataset.com/file-handling/?packageID=3

!wget https://github.com/justinkay/aldi/releases/download/v0.0.1/coco_car_annotations.json
!wget https://github.com/justinkay/aldi/releases/download/v0.0.1/cityscapes_train_instances_cars.json
!wget https://github.com/justinkay/aldi/releases/download/v0.0.1/cityscapes_val_instances_cars.json

!tar -xzf /content/sim10k.tar.gz

!unzip /content/leftImg8bit_trainvaltest.zip

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/justinkay/aldi
# %cd aldi
!pip install -e .

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/aldi/aldi/datasets.py
# 
# from detectron2.data.datasets import register_coco_instances
# register_coco_instances("sim10k_train", {}, "/content/coco_car_annotations.json", "/content/VOC2012/JPEGImages")
# register_coco_instances("cityscape_train", {}, "/content/cityscapes_train_instances_cars.json", "/content/leftImg8bit/train")
# register_coco_instances("cityscape_val", {}, "/content/cityscapes_val_instances_cars.json", "/content/leftImg8bit/val")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/aldi/configs/sim10k/Base-RCNN-FPN-Sim10k_strongaug_ema.yaml
# 
# _BASE_: "../Base-RCNN-FPN.yaml"
# MODEL:
#   ROI_HEADS:
#     NUM_CLASSES: 1
#   WEIGHTS: ""
# DATASETS:
#   TRAIN: ("cityscape_train",)
#   TEST: ("cityscapes_val",)
# EMA:
#   ENABLED: False
# SOLVER:
#   STEPS: (2999,)
#   MAX_ITER: 3000
#   CHECKPOINT_PERIOD: 1000
# TEST:
#   EVAL_PERIOD: 100
# OUTPUT_DIR: "output/sim10k/sim10k_baseline_strongaug_ema/"

!python tools/train_net.py --config /content/aldi/configs/sim10k/Base-RCNN-FPN-Sim10k_strongaug_ema.yaml

**Comment by Autobot37** [comment]
LOGS

WARNING [08/31 10:45:48 d2.data.datasets.coco]: 
Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you.

[08/31 10:45:48 d2.data.datasets.coco]: Loaded 2975 images in COCO format from /content/cityscapes_train_instances_cars.json
[08/31 10:45:48 d2.data.build]: Removed 144 images with no usable annotations. 2831 images left.
[08/31 10:45:48 d2.data.build]: Distribution of instances among all 1 categories:
|  category  | #instances   |
|:----------:|:-------------|
|    car     | 26900        |
|            |              |
[08/31 10:45:48 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=(800, 832, 864, 896, 928, 960, 992, 1024), max_size=2048, sample_style='choice'), RandomFlip(), SaveImgAug(savename='img_weak')]
[08/31 10:45:48 d2.data.common]: Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
[08/31 10:45:48 d2.data.common]: Serializing 2831 elements to byte tensors and concatenating them all ...
[08/31 10:45:48 d2.data.common]: Serialized dataset takes 10.69 MiB
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
[08/31 10:45:48 d2.checkpoint.detection_checkpoint]: [DetectionCheckpointer] Loading from  ...
[08/31 10:45:48 fvcore.common.checkpoint]: No checkpoint found. Initializing model from scratch
[08/31 10:45:48 d2.engine.train_loop]: Starting training from iteration 0
/usr/local/lib/python3.10/dist-packages/torch/functional.py:513: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3609.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
ERROR [08/31 10:47:04 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/detectron2/engine/train_loop.py", line 155, in train
    self.run_step()
  File "/usr/local/lib/python3.10/dist-packages/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/content/aldi/aldi/dropin.py", line 104, in run_step
    loss_dict = self.run_model(data)
  File "/content/aldi/aldi/trainer.py", line 130, in run_model
    return run_model_labeled_unlabeled(self, *data)
  File "/content/aldi/aldi/trainer.py", line 101, in run_model_labeled_unlabeled
    do_training_step(labeled_weak, "source_weak", lambda k: do_weak or (do_align and "_da_" in k), do_align=do_align)
  File "/content/aldi/aldi/trainer.py", line 87, in do_training_step
    loss = model(data[batch_i:batch_i+model_batch_size], **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/aldi/aldi/model.py", line 27, in forward
    return super(ALDI, self).forward(batched_inputs, do_align=do_align, labeled=labeled)
  File "/content/aldi/aldi/align.py", line 64, in forward
    output = super().forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/detectron2/modeling/meta_arch/rcnn.py", line 161, in forward
    proposals, proposal_losses = self.proposal_generator(images, features, gt_instances)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1603, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/detectron2/modeling/proposal_generator/rpn.py", line 477, in forward
    proposals = self.predict_proposals(
  File "/usr/local/lib/python3.10/dist-packages/detectron2/modeling/proposal_generator/rpn.py", line 503, in predict_proposals
    return find_top_rpn_proposals(
  File "/usr/local/lib/python3.10/dist-packages/detectron2/modeling/proposal_generator/proposal_utils.py", line 108, in find_top_rpn_proposals
    raise FloatingPointError(
FloatingPointError: Predicted boxes or scores contain Inf/NaN. Training has diverged.
[08/31 10:47:04 d2.engine.hooks]: Total training time: 0:00:09 (0:00:00 on hooks)
[08/31 10:47:04 d2.utils.events]:  iter: 2  total_loss: 2.927e+07  loss_cls_source_weak: 7.903e+05  loss_box_reg_source_weak: 2.839e+07  loss_rpn_cls_source_weak: 1.794e+04  loss_rpn_loc_source_weak: 6.752e+04    data_time: 9.3303  last_data_time: 8.2125   lr: 0.001194  max_mem: 5019M
2024-08-31 10:47:05.369061: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-31 10:47:05.395660: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-31 10:47:05.404343: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-31 10:47:05.425656: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-31 10:47:07.295845: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/aldi/tools/train_net.py", line 70, in <module>
    launch(
  File "/usr/local/lib/python3.10/dist-packages/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "/content/aldi/tools/train_net.py", line 65, in main
    return trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/detectron2/engine/defaults.py", line 484, in train
    super().train(self.start_iter, self.max_iter)
  File "/usr/local/lib/python3.10/dist-packages/detectron2/engine/train_loop.py", line 155, in train
    self.run_step()
  File "/usr/local/lib/python3.10/dist-packages/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/content/aldi/aldi/dropin.py", line 104, in run_step
    loss_dict = self.run_model(data)
  File "/content/aldi/aldi/trainer.py", line 130, in run_model
    return run_model_labeled_unlabeled(self, *data)
  File "/content/aldi/aldi/trainer.py", line 101, in run_model_labeled_unlabeled
    do_training_step(labeled_weak, "source_weak", lambda k: do_weak or (do_align and "_da_" in k), do_align=do_align)
  File "/content/aldi/aldi/trainer.py", line 87, in do_training_step
    loss = model(data[batch_i:batch_i+model_batch_size], **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/aldi/aldi/model.py", line 27, in forward
    return super(ALDI, self).forward(batched_inputs, do_align=do_align, labeled=labeled)
  File "/content/aldi/aldi/align.py", line 64, in forward
    output = super().forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/detectron2/modeling/meta_arch/rcnn.py", line 161, in forward
    proposals, proposal_losses = self.proposal_generator(images, features, gt_instances)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1603, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/detectron2/modeling/proposal_generator/rpn.py", line 477, in forward
    proposals = self.predict_proposals(
  File "/usr/local/lib/python3.10/dist-packages/detectron2/modeling/proposal_generator/rpn.py", line 503, in predict_proposals
    return find_top_rpn_proposals(
  File "/usr/local/lib/python3.10/dist-packages/detectron2/modeling/proposal_generator/proposal_utils.py", line 108, in find_top_rpn_proposals
    raise FloatingPointError(
FloatingPointError: Predicted boxes or scores contain Inf/NaN. Training has diverged.

**Comment by justinkay** [comment]
Looks like you are trying to train starting from random weights because you changed `MODEL.WEIGHTS: ""` ImageNet or COCO pre-training will be more stable. Either way, reducing the learning rate will probably help; see https://github.com/justinkay/aldi/issues/9

**Comment by Autobot37** [comment]
Means i have to do pre-training on Imagenet before burn-in?
Anyway thank you so much, loading weights from releases worked.

**Comment by justinkay** [comment]
Using a backbone that was pre-trained on ImageNet or COCO will help stabilize training and lead to better results - sounds like you were able to find the right weights. Training from scratch is probably also possible but I have not tried, it might be tricky to stabilize training early on.
