### ISSUE TITLE
KeyError: 'Non-existent config key

### ISSUE THREAD

**Issue by helia-mohamadi** [justinkay/aldi#51]
Hello @justinkay, 
I want to add new loss function to code. I added the config in config.py and config Yaml but I have this error: 

Command Line Args: Namespace(config_file='/home/ALDI/configs/ALDI-Best-car.yaml', resume=False, eval_only=False, num_gpus=1, num_machines=1, machine_rank=0, dist_url='tcp://', opts=[])
Traceback (most recent call last):
  File "/home/ALDI/tools/train_net.py", line 75, in <module>
    launch(
  File "/home/miniconda3/envs/ALDI/lib/python3.10/site-packages/detectron2-0.7-py3.10-linux-x86_64.egg/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "/home/ALDI/tools/train_net.py", line 50, in main
    cfg = setup(args)
  File "/home/ALDI/tools/train_net.py", line 39, in setup
    cfg.merge_from_file(args.config_file)
  File "/home/miniconda3/envs/ALDI/lib/python3.10/site-packages/detectron2-0.7-py3.10-linux-x86_64.egg/detectron2/config/config.py", line 69, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/home/miniconda3/envs/ALDI/lib/python3.10/site-packages/fvcore-0.1.5.post20221221-py3.10.egg/fvcore/common/config.py", line 132, in merge_from_other_cfg
  File "/home/miniconda3/envs/ALDI/lib/python3.10/site-packages/yacs-0.1.8-py3.10.egg/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/miniconda3/envs/ALDI/lib/python3.10/site-packages/yacs-0.1.8-py3.10.egg/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/miniconda3/envs/ALDI/lib/python3.10/site-packages/yacs-0.1.8-py3.10.egg/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/miniconda3/envs/ALDI/lib/python3.10/site-packages/yacs-0.1.8-py3.10.egg/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: DOMAIN_ADAPT.ALIGN.LOSS_ENABLED'

**Comment by justinkay** [comment]
Hi @helia-mohamadi you need to register any new config values with Detectron2, as we do in `config.py`: https://github.com/justinkay/aldi/blob/main/aldi/config.py

You can do this either by modifying `config.py` to add the new values or creating a new method similar to `add_aldi_config`

**Comment by helia-mohamadi** [comment]
Thank you.

**Comment by helia-mohamadi** [comment]
Hello again @justinkay,
Thank you.
I did what you said, but this error still hasn't been resolved.

# Begin domain adaptation settings
    _C.DOMAIN_ADAPT = CN()

    # Source-target alignment
    _C.DOMAIN_ADAPT.ALIGN = CN()
    _C.DOMAIN_ADAPT.ALIGN.IMG_DA_ENABLED = False
    _C.DOMAIN_ADAPT.ALIGN.IMG_DA_LAYER = "p2"
    _C.DOMAIN_ADAPT.ALIGN.IMG_DA_WEIGHT = 0.01
    _C.DOMAIN_ADAPT.ALIGN.IMG_DA_INPUT_DIM = 256 # = output channels of backbone
    _C.DOMAIN_ADAPT.ALIGN.IMG_DA_HIDDEN_DIMS = [256,]
    _C.DOMAIN_ADAPT.ALIGN.INS_DA_ENABLED = False
    _C.DOMAIN_ADAPT.ALIGN.INS_DA_WEIGHT = 0.01
    _C.DOMAIN_ADAPT.ALIGN.INS_DA_INPUT_DIM = 1024 # = output channels of box head
    _C.DOMAIN_ADAPT.ALIGN.INS_DA_HIDDEN_DIMS = [1024,]

    # Add KD Loss configuration
    _C.DOMAIN_ADAPT.ALIGN.KD_ENABLED = False
    _C.DOMAIN_ADAPT.ALIGN.KD_WEIGHT = 0.01

**Comment by justinkay** [comment]
The KeyError is due to `DOMAIN_ADAPT.ALIGN.LOSS_ENABLED`, which I don't see in this config. Try adding it?

**Comment by helia-mohamadi** [comment]
KD_ENABLED is LOSS_ENABLED that I added to config. 

Also, I realized that any changes I make to the code and expect to see their effects do not take effect by modifying the existing code structure. Instead, I must apply the changes directly to the following path:  
`/home/miniconda3/envs/ALDI/lib/python3.10/site-packages/aldi-0.1.1-py3.10.egg`  
to make them functional.  

Has this happened to you before, or do you have any idea why this might be occurring?

**Comment by helia-mohamadi** [comment]
Hi @justinkay, KD_ENABLED is LOSS_ENABLED that I added to config.

Also, I realized that any changes I make to the code and expect to see their effects do not take effect by modifying the existing code structure. Instead, I must apply the changes directly to the following path:
/home/miniconda3/envs/ALDI/lib/python3.10/site-packages/aldi-0.1.1-py3.10.egg
to make them functional.

Has this happened to you before, or do you have any idea why this might be occurring?
